[package]
name = "photondb"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["The PhotonDB Authors"]
homepage = "https://photondb.io"
repository = "https://github.com/photondb/photondb"
description = "A storage engine for modern hardware."

[dependencies]
async-trait = "0.1.57"
bitflags = "1.3.2"
futures = "0.3.24"
photonio = "0.0.4"
thiserror = "1.0.37"

[profile.bench]
debug = true

[profile.release]
debug = true
